variables:
  BUILD_DIR: 'build'
  COVERAGE_DIR: 'target/site/jacoco'

stages:
 - build stage
 - coverage stage

build:
  variables:
    QT_QPA_PLATFORM: "offscreen"
  dependencies: []
  tags:
    - linux
  stage: build stage
  script:
    - mvn package
  only: ['merge_requests', 'master']
  artifacts:
    name: "build artifacts"
    paths:
     - $BUILD_DIR
     - $COVERAGE_DIR
    expire_in: 10 hrs