variables:
  BUILD_DIR: 'build'

stages:
 - build stage

build_linux:
  variables:
    QT_QPA_PLATFORM: "offscreen"
  dependencies: []
  tags:
    - linux
  stage: build stage
  script:
    - mvn package
    - rm -rf target/
  only: ['merge_requests', 'master']
  artifacts:
    name: "build artifacts"
    paths:
     - $BUILD_DIR
    expire_in: 10 hrs
